name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload Jacoco coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/index.html

      - name: Publish artifact to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: recept-nyilvanto-artifact
          path: target/recept-nyilvanto-*.jar

      - name: Publish artifact to GitHub Packages (maven)
        run: |
          mvn deploy:deploy-file \
            -DgroupId=com.example \
            -DartifactId=recept-nyilvanto \
            -Dversion=1.0.0 \
            -Dfile=target/recept-nyilvanto-1.0.0.jar \
            -DrepositoryId=github-packages \
            -Durl=https://maven.pkg.github.com/yourusername/recept-nyilvanto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
