name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kód klónozása
        uses: actions/checkout@v3

      - name: Java 17 beállítása
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven build és teszt
        run: mvn clean verify

      - name: Jacoco HTML riport elmentése
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Maven settings.xml létrehozása
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
            xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
            xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <servers>
              <server>
                <id>github</id>
                <username>Vlukacs0</username>
                <password>${{ secrets.MY_PAT }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Artifact deploy GitHub Packages-re
        run: mvn deploy
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

      - name: Checkstyle futtatása
        run: mvn checkstyle:check
